//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incidencias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraTickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CabeceraTickets()
        {
            this.LineasTicket = new HashSet<LineasTicket>();
        }
    
        public int Id { get; set; }
        public string FechaApertura { get; set; }
        public string FechaCierre { get; set; }
        public int TiempoTotal { get; set; }
        public bool Facturable { get; set; }
        public string ClientesCif { get; set; }
        public int ProductosId { get; set; }
        public string Tipo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Productos Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineasTicket> LineasTicket { get; set; }
    }
}
