//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incidencias.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> ClientesSet { get; set; }
        public virtual DbSet<Productos> ProductosSet { get; set; }
        public virtual DbSet<CabeceraTickets> CabeceraTicketsSet { get; set; }
        public virtual DbSet<LineasTicket> LineasTicketSet { get; set; }
        public virtual DbSet<Tecnicos> TecnicosSet { get; set; }
    }
}
